### ISSUE TITLE
404 for predicting-milestones.html

### ISSUE THREAD

**Issue by koalie** [w3c/Guide#10]
https://www.w3.org/Guide/standards-track/predicting-milestones.html is a 404 but https://w3c.github.io/Guide/standards-track/predicting-milestones.html isn't. I can't fix, because of all the .htaccess I don't understand.

**Comment by tripu** [comment]
[Replacing `standards-track` with `process`] both forms work now:

* [`https://www.w3.org/Guide/process/predicting-milestones.html`](https://www.w3.org/Guide/process/predicting-milestones.html)
* [`https://w3c.github.io/Guide/process/predicting-milestones.html`](https://w3c.github.io/Guide/process/predicting-milestones.html)

**Comment by plehegar** [comment]
Thank you @tripu
