### ISSUE TITLE
Missing https://www.w3.org/Guide/pubrules-style.css

### ISSUE THREAD

**Issue by tripu** [w3c/Guide#11]
The file is where it's supposed to be, but a redirection is hiding it behind a 404 coming from GitHub.

@iherman says that *&ldquo;newer charters rely on this CSS[&hellip;], so they do not display correctly :-(&rdquo;*.

Note that this might be happening to a few other files under the same directory, too.

**Comment by iherman** [comment]
Note that this affects already published charters, like [pwg charter](https://www.w3.org/2017/04/publ-wg-charter/).

**Comment by plehegar** [comment]
we have a redirect in place for this. feel free to re-open if this is still an issue.
