### ISSUE TITLE
Teleconferences' page is outdated... 

### ISSUE THREAD

**Issue by iherman** [w3c/Guide#147]
The guide refers to https://www.w3.org/Guide/1998/08/TeleconferenceHowTo which was created for WebEx and is, I presume, out of date. I did not find and member visible page on zoom (only a [team only page on zoom](https://www.w3.org/Team/wiki/Zoom)) to replace the reference with.

**Comment by plehegar** [comment]
fyi, the right page is https://www.w3.org/Guide/meetings/zoom
