### ISSUE TITLE
"Join a group" link has rotted

### ISSUE THREAD

**Issue by jyasskin** [w3c/Guide#155]
The "Join a group" link on https://www.w3.org/Guide/ goes to https://www.w3.org/2004/01/pp-impl/, which redirects to https://www.w3.org/groups/, which doesn't explain how to join a group.

**Comment by svgeesus** [comment]
I agree there is no explanation on how to join a group. https://www.w3.org/groups/, lets you go to the list of WG and then to a particular WG and if you click on "Summary" for any group there is a link "Join the group" and also "Manage your organization's participation" but that is non-obvious unless you already know it.

So yes there should be an explanation page about how to join a WG, an IG, a BG, or a CG and also explaining about AC Reps and Invited experts in other words who can join which sort of group.

**Comment by plehegar** [comment]
I replaced it with a link to the FAQ instead. I'd rather not duplicate the wording on how to join a Group.
See [diff](https://github.com/w3c/Guide/commit/b8f949730f610233b1ddb4c59f39779f275cc544#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R132)
