### ISSUE TITLE
Adding a link to CSSWG Services section

### ISSUE THREAD

**Issue by astearns** [w3c/Guide#164]
I’d like to see the Services section for the CSSWG include this link, which is currently the best introduction we have for new members:

Introduction to CSSWG process: https://fantasai.inkedblade.net/weblog/2011/inside-csswg/

I started poking around to see where I could add this, and it wasn’t immediately obvious.

**Comment by plehegar** [comment]
https://github.com/w3c/onboarding contains the templates used when someone new joins a Group. Those could be tailored as needed.

Group have 2 public homepages:
* the default ones: intended for a large public audience. We do require consistency among those.
* the group ones: linked from the default homepage, they contain information that could be tailored at will.

I suggest adding the link to the CSSWG group page, as well as the onboarding email.

**Comment by plehegar** [comment]
@astearns @svgeesus , feel free send a PR to change the CSSWG onboarding email (and assign it to me if you can't merge)

**Comment by plehegar** [comment]
[CSS onboarding template](https://github.com/w3c/onboarding/blob/master/template/32061)
