### ISSUE TITLE
Add Council to /Guide

### ISSUE THREAD

**Issue by fantasai** [w3c/Guide#166]
We'll need to add documentation to /Guide about Formal Objection handling with the Council.

As part of that we should merge in any useful text from these documents, and also deprecate (and redirect) them:

- https://github.com/w3c/AB-memberonly/blob/master/documents/FormalObjectionCouncilGuide.md
- https://www.w3.org/2017/12/formal-objections.html

**Comment by plehegar** [comment]
addressed in #172
