### ISSUE TITLE
Link from council guide to DirectorFOdashboard

### ISSUE THREAD

**Issue by jyasskin** [w3c/Guide#226]
The other day I was trying to find https://www.w3.org/Member/wiki/DirectorFOdashboard, but when I looked for a link from https://www.w3.org/Guide/council/council, I couldn't find one.

I could imagine putting a link to https://www.w3.org/Member/wiki/DirectorFOdashboard#Team_is_attempting_to_find_consensus_or_not_ready_to_ask_a_Council in https://www.w3.org/Guide/council/council#team-fo and a link to https://www.w3.org/Member/wiki/DirectorFOdashboard#Team_has_determined_consensus_cannot_be_found_and_needs_a_decision in https://www.w3.org/Guide/council/council#referral, but I'd also be happy with a different arrangement.

**Comment by mnot** [comment]
Considering that it's a critical governance mechanism, I'd expect it to also be listed on w3.org/Member -- although that page is quite the mess right now. We really need to streamline and rework all of this.

**Comment by jyasskin** [comment]
I'd rather not expand the scope of this issue to reworking the whole Member Home, or even the whole introductory material for AC reps. Feel free to file new issues for other cross-links that should be added. The Guide repo might not be the right place for all of those issues, although I don't have a better place to suggest.

**Comment by mnot** [comment]
Of course.

**Comment by plehegar** [comment]
Good catch. And yes, that wiki page needs to be moved/get renamed/etc.
