### ISSUE TITLE
Remove references to Director from Guidelines to suspend or remove participants from groups

### ISSUE THREAD

**Issue by gsnedders** [w3c/Guide#246]
https://www.w3.org/Guide/process/suspension.html, referenced from [Process](https://www.w3.org/policies/process/20231103/#discipline), still talks about the powers of the Director. This no longer matches the Process document (now there is no Director), which exclusively and explicitly gives this power to the CEO.

**Comment by plehegar** [comment]
Done in https://github.com/w3c/Guide/commit/c9a8fc3551a0800d7699ef38956f7dfc15df1f23 (and follow-up commits).

Thanks to @koalie
