### ISSUE TITLE
Revamp /Guide; making is really usable 

### ISSUE THREAD

**Issue by koalie** [w3c/Guide#34]
@nrooney and/or anyone from the WGE TF can say more, but there's a request to revamp /Guide and make it really useable (sic).

The W3C internal webdesign task force may be able to help.

**Comment by nrooney** [comment]
We've taken a stab at an architecture, but it's still evolving:
https://github.com/w3c/wg-effectiveness/blob/master/guide_arch.md

**Comment by nrooney** [comment]
Now working on the `mock_guide` branch on this repo
