### ISSUE TITLE
Group specific pages

### ISSUE THREAD

**Issue by nrooney** [w3c/Guide#42]
Have group specific pages section which explains tools specific for those group. CSS group is a good example.

**Comment by nigelmegitt** [comment]
CSS pages, for example:

* https://wiki.csswg.org/ CSS WG wiki
* https://wiki.csswg.org/tools CSS WG Tools

**Comment by plehegar** [comment]
We now have tools pages across all of our groups, eg [CSS](https://www.w3.org/groups/wg/css/tools), [Timed Text](https://www.w3.org/groups/wg/timed-text/tools).

The information on those pages are coming from:
- team contacts, using the [service entries](https://api.w3.org/doc#operations-tag-Services) in the W3C DB.
- Github repositories list come our [crawl of w3c.json files](https://github.com/w3c/groups) in GitHub.

Those pages do not explain the tools themselves however, so more needs to happen.

**Comment by plehegar** [comment]
closing for now unless someone believes further action is needed
