### ISSUE TITLE
Continuity of Operations

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#57]
Continuity of Operations under Travel Restrictions
https://w3c.github.io/Guide/meetings/continuity.html

Currently states: "Groups should plan to make extensive use of video conferencing services for those unable to travel.  If a substantial number of participants are unable to travel the group is encouraged to conduct the meeting entirely by video conference, avoiding even local "hubs".  The goal is to put all the meeting participants on equal terms."

It may be more useful to encourage meeting organizers to note that there are many different modes of telepresence and/or remote gatherings. In the case of travel restrictions for some but not all participants, those without travel restrictions might want to gather in a hub, and it is unclear that the benefit for those individuals would somehow adversely affect the experience of those who couldn't gather in hubs. Equitable participation could be assured by following good communication and meeting participation practices, rather than by depriving those who can gather of the opportunity to do so.

Instead of imposing constraints on options for gathering, W3C could commit to accommodate mixed-mode meetings, including high quality remote participation options for one, some, most, or all the participants in a gathering.

**Comment by swickr** [comment]
Thanks @brewerj.  In 57d7e9ff8509e44713f3c2046c628fff3987c52b I revised this to allow hubs but with attention to equitable treatment of all participants.

**Comment by plehegar** [comment]
@brewerj , we believe this issue as addressed and plan to close it by Tuesday next week unless further comments are provided. Please make sure to read the latest version of the document.

**Comment by plehegar** [comment]
Note that I did add a sentence: "It is however acceptable to continue to have social hub gatherings outside of the meeting. "

**Comment by brewerj** [comment]
The addition of that follow-on sentence about social hub gatherings being acceptable seems to negate the clarification you just provided social hub gatherings being OK as long as you treat people equitably. If we've just said it's OK, why would we need to clarify that people can go off to bars if they want to take that risk?

**Comment by swickr** [comment]
I concur with Judy on the apparent contradiction.  I don't, however, think W3C<sup>*</sup> can ban social gatherings.  Would the following changes help?:

> It is however acceptable to /-continue to-/ have social hub gatherings outside of the meeting /+provided that any business conversations be summarized at the next group meeting for those who were not present at the social gathering+/.

----

<sup>*</sup> as distinct from what government authorities might do to control community transmission of contagion.

**Comment by brewerj** [comment]
I think the cleanest solution is dropping the sentence. It may have been necessary in the previous context, but unnecessary now. And the current situation is too complicated given the possibility of bans in local jurisdictions, far beyond what W3C needs to make a statement on.

**Comment by swickr** [comment]
I am OK dropping it now; as you note, circumstances beyond our control are now dictating what individuals are able to do.

**Comment by brewerj** [comment]
Clearer, thx.
