### ISSUE TITLE
AC Meeting duration

### ISSUE THREAD

**Issue by koalie** [w3c/Guide#58]
I think our guidelines for "W3C AC Meeting" ought to include a specific "Meeting duration" recommendation because assuming that we recommend that this particular meeting be fully remote (no hub --in either case, this could be clarified), I believe the meeting duration described under "Arrangements for Virtual Presence" is appropriate, provided that the AC Meeting spans more days than our habitual two.

(We typically have a 12-hour agenda spread over 2 days.)

**Comment by chaals** [comment]
Makes sense to limit the amount of time people are in teleconference, and have decent-sized breaks. If people have set aside time in advance, then using that day but with significant timeout chunks for interruptions and naps is probably more helpful than trying to find big chunks of time over more days... But people's mileage probably varies considerably.

**Comment by swickr** [comment]
The notion as of 3 March is to have the synchronous discussion sessions in two 90-minute segments on two consecutive days.   The recorded presentations should be available a week in advance to allow participants to schedule their own viewing times.

**Comment by plehegar** [comment]
I believe this is now addressed by the document. I'll close this issue on Tuesday next week unless further comments are added here.
