### ISSUE TITLE
Add a workshop section

### ISSUE THREAD

**Issue by koalie** [w3c/Guide#59]
With several workshops in the pipe (one cancelled already), how do we plan for  workshops during travel resctriction times?
(via @wseltzer)

**Comment by plehegar** [comment]
The document was updated to make sure the default expectation is to not cancel meetings and continue our operations as normal. @swickr will make additional updates. Not closing this issue for now.

**Comment by wseltzer** [comment]
I added more, and as Strat lead, felt empowered to merge the PR.

**Comment by swickr** [comment]
Thanks Wendy.  @koalie I propose to close this general issue.  Specific suggestions on the [Workshop](https://www.w3.org/Guide/meetings/continuity#workshops) section can be new issues.
