### ISSUE TITLE
Continuity of Operations >> Purpose >> travel constraints

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#61]
In continuity of operations document, purpose section, you mention: 

"This document outlines contingency plans due to (international) travel restrictions"

Given where we are now on Covid-19, the qualifying parenthetical adjective "international" seems unnecessary at this point, as travel restrictions are now on multiple levels. 

Simply removing the parenthetical would resolve the issue.

**Comment by swickr** [comment]
Addressed in https://github.com/w3c/Guide/commit/654d49c6f75cb7baeef2a302dbdbc59751f7a63c - I propose to close this issue.
