### ISSUE TITLE
Continuity of Operations >> Different Meetings

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#62]
In Continuity of Operations, under "Different Meetings" you note that TPAC 2020 is, as of 13 March 2020, happening as planned, on 26-30 October 2020, in Vancouver BC, Canada. 

Good place to demonstrate that we have already announced that we are virtualizing the AC Meeting originally planned for Seoul in May.

**Comment by brewerj** [comment]
I noticed after making this comment that there is a whole section on virtualization of the AC meeting lower down in the document. I would suggest making a quick reference and link to that in the  "Different Meetings" section, so that people don't wonder about the apparent omission, as I did.

**Comment by swickr** [comment]
Done https://github.com/w3c/Guide/commit/f324205ccc63c66e3593349a09a172b5639d33c1

**Comment by brewerj** [comment]
Currently the last line of this section states "Note: AC 2020 (member link) will be a distributed meeting and TPAC 2020 (member link) is, as of 13 March 2020, happening as planned, on 26-30 October 2020, in Vancouver BC, Canada."
Minor issue but after after re-reading it a few times and finding it difficult to parse, I suggest: 

Note: 
- AC 2020 (member link) will be a virtual presence meeting
- TPAC 2020 (member link) will, as of 13 March 2020, take place as planned on 26-30 October 2020, in Vancouver BC, Canada, though we will explore contingency back-up plans for a virtual meeting as needed.
