### ISSUE TITLE
Continuity of Operations >> Use of videoconferencing

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#63]
"Video cameras are strongly encouraged; this improves the sense of being together.  Groups may prefer to use teleconferencing services that allow each participant to choose not to receive video streams if their network becomes saturated."

Please add a cautionary note:  Please note that not all participants may be able to see each other on a videoconference. This may be because of visual capabilities of devices, or capabilities of participants. 

Please be sure to at least provide informal real-time descriptions of video action, to keep people informed if they are not able to directly view their presention,

**Comment by swickr** [comment]
Two issues here; the social proximity provided by a video feed of participants' faces is not easily communicated via other means.  (Though smiles and "thumbs-up" expressions have conventions in both teleconference systems and irc.)

Separately, video of content that is being discussed, such as screen sharing, should certainly be augmented with an accessible description.

This is now addressed by https://github.com/w3c/Guide/commit/ac1044425e19af1d0a19b7376ed375249975c181

**Comment by brewerj** [comment]
LGTM, thx
