### ISSUE TITLE
Continuity of Operations >> AC meeting >> Captioning

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#64]
"High quality real-time transcription of the meeting should be provided in more than one language." 

This should be "high-quality real-time captioning."

Use of "transcription" here muddies the waters. [More info https://www.w3.org/WAI/media/av/]

**Comment by swickr** [comment]
Yup; done https://github.com/w3c/Guide/commit/9a427a2b3bc4768ead5f60b7e894324b0ce98526
