### ISSUE TITLE
Continuity of Operations >> Meeting Duration

### ISSUE THREAD

**Issue by brewerj** [w3c/Guide#67]
"Meeting duration should be limited to 4 hours per day; consider two 90-minute segments with an hour break between them.  That break can be used by the participants for "hallway" conversations, arranged on separate conference channels."

Is this proposed as a W3C rule, or as a recommended best practice? Is it due to concerns about duration of hours that people are on videoconferences overall, or concerns on a per-group basis? Or because it's assumed that every meeting will bridge most time-zones? Many will, but probably not all. 

In the case where a meeting is mixed-mode (some participants face-to-face, and some remote) capping a meeting to four hours could create odd results, for instance disadvantaging people who have gathered, or disadvantaging people who must be remote but are actually in the same time zone and available for longer. 

Please consider raising the issue of meeting duration to people's awareness, and recommending a four-hour cap as a best practice, but also adding a preamble to the document recommending that these best practices should be read and discussed as needed, but that negotiated exceptions are acceptable if the group consenses those exceptions. 

Generally, some of the document has a tone of "considerations to take into account;" other parts "recommended practices"; and yet others as "you must to do this." +1 to "please consider" and -1 to "must" unless the requirement is well-backed up by information or experience.

**Comment by nigelmegitt** [comment]
As a matter of good practice, if I have a meeting that is >=2 hours long, I encourage some kind of break, standing up for a bit, for 2-3 minutes after each hour. Might be worth adding as a suggestion, to keep meeting energy up.

**Comment by swickr** [comment]
duplicates #60

**Comment by swickr** [comment]
I acknowledge your advice, @brewerj , to distinguish among considerations, recommendations, and directives.  In #60 I suggested that in this document all "shoulds" be interpreted as guidelines to aid the meeting chair(s) in making choices and enforcing those choices.

**Comment by brewerj** [comment]
WFM, thx
