### ISSUE TITLE
Recusing versus acting as code of conduct ‘accuser’

### ISSUE THREAD

**Issue by astearns** [w3c/Guide#98]
I am concerned about this scenario (which has played out several times for me)

1. As a group chair, I see a non-member harassing people in our repo.
2. I warn them to follow our CEPC
3. They continue and/or escalate their harassment
4. I act to ban them (asking a team contact or sysreq to help)

I *think* for this I am the accuser, and there’s a sentence that says I should recuse myself in that case. Is that the intent (that I should find someone else to do step 4, or wait until someone else complains before step 2)?

**Comment by wseltzer** [comment]
@astearns, which document are you looking at? It's appropriate for the chair to warn and take action against harassment, and I don't see a call for recusal in [CEPC](https://www.w3.org/Consortium/cepc).

**Comment by astearns** [comment]
https://github.com/w3c/Guide/blob/27b0b587ab54c1e1be05d475613e5bb1d623744c/process/banning.html#L58

“If the chair, team contact, CEO, COO are involved as accused or accuser, they should recuse themselves from all discussions.”

**Comment by wseltzer** [comment]
thanks, will look into that.

**Comment by wseltzer** [comment]
Our goal in the Guide is
* to enable chairs to act in real-time when needed
* to give all an opportunity for review by an uninvolved party (which could be after the fact, when prompt action is needed)

Your first proposal, asking a co-chair or team contact to take action when you identify problematic behavior, would work. Do you think that would be sufficient? 

While I'm trying to improve the Guidebook, if you have any specific issues, please get in touch with me or an Ombuds, as necessary.

**Comment by astearns** [comment]
I think that’s fine - more deliberation on banning is good, and for most actions I need to convince a team contact anyway.

Given this, and that some groups do not have co-chairs, would it make sense to delegate to team contacts as well as chairs here?

https://github.com/w3c/Guide/blob/27b0b587ab54c1e1be05d475613e5bb1d623744c/process/banning.html#L55
